services:
  - type: web
    name: collection-form-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --workers 4
    envVars:
      - key: DB_SERVER
        value: DESKTOP-RMNV9QV\A2006
      - key: DB_NAME
        value: AED_AssignmentOne
      - key: DB_USER
        value: sa
      - key: DB_PASSWORD
        value: oCt2005-ShenZhou6_A2006