name = "collection-form"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "FORM_DATA"
id = "1e980c8c22084d088f192e18d5d9e9d9"

[site.assets]
include = ["public/**/*"] 