name = "collection-form"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"
include = ["public/**/*"]
exclude = []

[[kv_namespaces]]
binding = "FORM_DATA"
id = "1e980c8c22084d088f192e18d5d9e9d9"

# Remove build command since we're using Streamlit Cloud
# [build]
# command = "pip install -r requirements.txt"

# Add logging configuration
[observability]
[observability.logs]
enabled = true

# Add development settings
[dev]
port = 8787
local_protocol = "http" 