name = "collection-form"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"
include = ["public/**/*"]
exclude = []

[[kv_namespaces]]
binding = "FORM_DATA"
id = "9992ed9592824f479199b430befc6162"

[vars]
STREAMLIT_URL = "https://collection-form.streamlit.app"

[build]
command = "npm run build"

[env.production]
route = "collection-form.pages.dev/*"

[observability]
[observability.logs]
enabled = true

[dev]
port = 8787
local_protocol = "http"